image: golang:1.13.0-buster

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make
  artifacts:
     paths:
     - /go/bin/terraform-provider-hyperv
