image: golang:alpine

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - go build
  artifacts:
     paths:
     - terraform-provider-hyperv
